FROM php:7.3-apache

RUN apt-get clean
RUN apt-get update

#PHP intl extension
RUN apt-get update \
    && apt-get install -y libicu-dev \
    && docker-php-ext-install intl \
    && apt-get remove -y libicu-dev 

#Add git, zip and clean apt-get 
RUN apt-get install -y git \
  #&& zip \
    && apt-get autoremove -y \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

#Install Composer
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer
RUN chmod a+x /usr/local/bin/composer

#Restart Service Apache
RUN a2enmod rewrite